import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import AuthScreen from "../components/AuthScreen";
import ChatScreen from "../components/ChatScreen";
export default function Home() {
  const [isLoggedIn, setIsLoggedIn] = useState(false);

  return (
    <>
      <Head>
        <title>Realt Time Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{isLoggedIn ? <ChatScreen /> : <AuthScreen />}</main>
    </>
  );
}
